"""Regression test for controls whose boot bindings can silently disappear."""
import sys
sys.path.insert(0, __import__("os").path.dirname(__file__))
from cdp import App, Results

r = Results()
app = App(port=9452)
try:
    r.check("editor mounted", app.wait("!!document.querySelector('#editor .vditor-reset')"))
    r.check("shortcut screen restored", app.wait("!!document.getElementById('shortcut-screen')", 8))
    r.check("Shortcut Screen uses a compact left brand and the keyboard list", app.js("(() => { const m=document.getElementById('shortcut-screen'); return m.querySelector('.shortcut-screen-head h2').textContent === 'Shortcuts' && m.querySelectorAll('.wk-row').length > 50 && !m.querySelector('.welcome-highlights') && m.querySelector('.settings-brand-wordmark').getBoundingClientRect().width < 100; })()"))
    app.js("document.querySelector('#shortcut-screen .settings-brand-mark').click()")
    r.check("Shortcut Screen mark collapses sidebar", app.js("document.getElementById('outline-panel').classList.contains('collapsed')"))
    app.js("document.querySelector('#shortcut-screen .settings-brand-mark').click()")
    app.js("document.querySelector('#shortcut-screen .settings-brand-menu').click()")
    r.check("Shortcut Screen chevron opens the brand menu", app.js("!document.getElementById('brand-menu').hidden"))
    app.js("document.getElementById('btn-brand-menu').click()")
    app.js("document.querySelector('#shortcut-screen .shortcut-screen-close').click()")

    app.js("document.getElementById('side-tab-outline').click()")
    r.check("Outline tab opens", app.js("!document.getElementById('side-pane-outline').hidden && document.getElementById('side-tab-outline').classList.contains('active')"))
    r.check("Outline contains the current heading", app.js("document.querySelectorAll('#outline .outline-item').length > 0"))

    app.js("document.getElementById('btn-brand-logo').click()")
    r.check("logo mark collapses sidebar", app.js("document.getElementById('outline-panel').classList.contains('collapsed')"))
    app.js("document.getElementById('btn-brand-logo').click()")
    r.check("logo mark expands sidebar", app.js("!document.getElementById('outline-panel').classList.contains('collapsed')"))
    app.js("document.getElementById('btn-brand-menu').click()")
    r.check("chevron opens the brand menu", app.js("!document.getElementById('brand-menu').hidden"))
    r.check("brand menu contains only the four specified icon entries", app.js("(() => { const b=[...document.querySelectorAll('#brand-menu > button')]; return b.length === 4 && b.every(x => !!x.querySelector('img')); })()"))
    app.js("document.getElementById('btn-brand-menu').click()")
    r.check("main-app brand is compact and left-aligned", app.js("(() => { const mark=document.getElementById('btn-brand-logo').getBoundingClientRect(), word=document.getElementById('brand-wordmark').getBoundingClientRect(), menu=document.getElementById('btn-brand-menu').getBoundingClientRect(); return mark.left <= 6 && menu.right < 180; })()"))
    r.check("format toolbar shares the top row and right-aligns with padding", app.js("(() => { const b=document.getElementById('toolbar').getBoundingClientRect(), brand=document.getElementById('brand-wrap').getBoundingClientRect(), t=document.querySelector('#toolbar .vditor-toolbar').getBoundingClientRect(); return t.left >= brand.right-1 && b.right-t.right >= 8 && t.top < b.bottom; })()"))
    r.check("word-count number is not shown in the toolbar", app.js("(() => { const c=document.querySelector('#toolbar .vditor-counter'); return !c || getComputedStyle(c).display === 'none'; })()"))
    r.check("main logo is half-size", app.js("(() => { const m=document.querySelector('#btn-brand-logo img').getBoundingClientRect(), w=document.getElementById('brand-wordmark').getBoundingClientRect(); return m.width <= 17 && w.width <= 51; })()"))
    r.check("toolbar wraps when available width shrinks", app.js("(() => { const b=document.getElementById('toolbar'), t=document.querySelector('#toolbar .vditor-toolbar'), old=b.style.width; b.style.width='420px'; const wraps=t.getBoundingClientRect().height > 30; b.style.width=old; return wraps; })()"))
    r.check("H, B, and i use matched glyph sizing and requested styles", app.js("(() => { const q=x=>document.querySelector(`#toolbar [data-type=\\\"${x}\\\"] .mdaddy-toolbar-glyph`); const h=q('headings'), b=q('bold'), i=q('italic'); return !!h&&!!b&&!!i&&h.getBoundingClientRect().width===b.getBoundingClientRect().width&&b.getBoundingClientRect().width===i.getBoundingClientRect().width&&getComputedStyle(h).fontWeight==='700'&&getComputedStyle(b).fontWeight==='700'&&getComputedStyle(i).fontStyle==='italic'; })()"))
    r.check("quote and task-list icons use the requested artwork", app.js("!!document.querySelector('#toolbar [data-type=quote] .mdaddy-quote-glyph') && !!document.querySelector('#toolbar [data-type=check] .mdaddy-check-glyph path')"))
    r.check("Reader, Find, and text-color controls have consistent unoutlined sizing", app.js("(() => { const ids=['btn-reader-toggle','btn-toolbar-find','text-color-button']; const bs=ids.map(id=>document.getElementById(id).getBoundingClientRect()); return bs.every(b=>b.width===bs[0].width&&b.height===bs[0].height) && ids.every(id=>getComputedStyle(document.getElementById(id)).borderStyle==='none' || getComputedStyle(document.getElementById(id)).borderWidth==='0px'); })()"))

    app.js("document.getElementById('btn-toolbar-find').click()")
    r.check("magnifier opens Find", app.js("!document.getElementById('find-bar').hidden"))
    app.js("document.getElementById('btn-toolbar-find').click()")
    r.check("magnifier closes Find", app.js("document.getElementById('find-bar').hidden"))

    app.js("document.getElementById('text-color-button').click()")
    r.check("text-color button opens palette", app.js("!document.getElementById('text-color-menu').hidden"))
    app.js("""(() => { const root=document.querySelector('#editor .vditor-reset'); const w=document.createTreeWalker(root,NodeFilter.SHOW_TEXT); let n; while(n=w.nextNode()) if(n.nodeValue.includes('Double-click')) { const range=document.createRange(); range.setStart(n,0); range.setEnd(n,6); const sel=getSelection(); sel.removeAllRanges(); sel.addRange(range); return true; } return false; })()""")
    app.js("document.getElementById('text-color-button').dispatchEvent(new PointerEvent('pointerdown',{bubbles:true,cancelable:true,pointerType:'mouse'})); document.getElementById('text-color-button').click(); document.querySelector('#text-color-menu [data-color=\"#b42318\"]').click()")
    r.check("text-color applies the selected color", app.js("[...document.querySelectorAll('#editor .vditor-reset span[style]')].some(s => s.textContent === 'Double' && s.style.color === 'rgb(180, 35, 24)')"))

    app.js("document.getElementById('btn-reader-toggle').click()")
    r.check("Reader Mode enters full editor", app.wait("!!document.querySelector('.vditor--fullscreen')", 4))
    app.js("document.getElementById('btn-reader-toggle').click()")
    r.check("Reader Mode returns to editing", app.wait("!document.querySelector('.vditor--fullscreen')", 4))

    app.js("document.getElementById('btn-brand-menu').click(); document.getElementById('brand-settings').click()")
    r.check("Settings opens the shortcut screen section", app.wait("!!document.querySelector('#settings-modal .shortcuts-filter')", 4))
    r.check("Settings header keeps the brand at the left", app.js("!!document.querySelector('#settings-modal .settings-brand-mark') && !!document.querySelector('#settings-modal .settings-brand-wordmark')"))
    app.js("document.querySelector('#settings-modal .settings-brand-mark').click()")
    r.check("settings logo mark collapses sidebar", app.js("document.getElementById('outline-panel').classList.contains('collapsed')"))
    app.js("document.querySelector('#settings-modal .settings-brand-mark').click()")
    r.check("settings logo mark expands sidebar", app.js("!document.getElementById('outline-panel').classList.contains('collapsed')"))
    app.js("document.querySelector('#settings-modal .settings-brand-menu').click()")
    r.check("settings chevron opens the same menu", app.js("!document.getElementById('brand-menu').hidden"))
    app.js("document.getElementById('btn-brand-menu').click()")
    r.check("shortcut startup option is in Shortcuts settings", app.js("document.querySelector('#settings-modal').innerText.includes('Show shortcut screen when Mdaddy starts')"))
    r.check("General settings section is absent", app.js("![...document.querySelectorAll('#settings-modal .settings-nav button')].some(b => b.textContent.trim() === 'General')"))
finally:
    app.close()

sys.exit(r.summary())
